# Generated by Django 2.2.4 on 2019-08-23 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0005_team_team_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='poster',
            field=models.ImageField(blank=True, upload_to='images'),
        ),
    ]
