# Generated by Django 2.2.4 on 2019-08-08 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='round',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='round',
            name='is_live',
            field=models.BooleanField(default=False),
        ),
    ]
