# Generated by Django 2.2.4 on 2019-08-09 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_auto_20190808_1750'),
    ]

    operations = [
        migrations.AddField(
            model_name='attempt',
            name='is_submitted',
            field=models.BooleanField(default=False),
        ),
    ]
