# Generated by Django 2.2.4 on 2019-08-13 05:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_attempt_is_submitted'),
    ]

    operations = [
        migrations.AddField(
            model_name='attempt',
            name='round',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='quiz.Round'),
        ),
        migrations.AddField(
            model_name='question',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='videos/'),
        ),
    ]
