# Generated by Django 2.2.4 on 2019-08-13 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0004_auto_20190813_0510'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='video',
        ),
        migrations.AddField(
            model_name='question',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='files/'),
        ),
    ]
