# Generated by Django 2.2.4 on 2019-08-19 20:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0006_bzrattempt_phase'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bzrattempt',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='team.Team'),
        ),
    ]
