# Generated by Django 2.2.4 on 2019-08-24 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0008_round_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='round',
            name='poster',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
    ]
