# Generated by Django 2.2.4 on 2019-08-11 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('score', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='score',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
